ci: Added docstring linting action

diff --git a/.github/workflows/pr-linting.yaml b/.github/workflows/pr-linting.yaml
--- a/.github/workflows/pr-linting.yaml
+++ b/.github/workflows/pr-linting.yaml
@@ -18,8 +18,20 @@ jobs:
         uses: "actions/checkout@v3"
       - name: "Code format"
         run: |
-          pip3 install isort pylint black
+          pip3 install isort pylint black darglint
           find . -name "*.py" -not -path "./tests/*" -exec python3 -m isort {} \; -exec python3 -m black {} \;
+      - name: "Docstring linting"
+        run: |
+          results=$(find . -name "*.py" -not -path "./tests/*" -exec darglint --docstring-style sphinx {} \;)
+  
+          if [[ -z "$results" ]]; then
+            echo "All docstrings are valid
+          else
+            echo "Invalid docstrings found:"
+            echo "$results"
+            exit 1
+          fi
+
       - name: "Commit linted files"
         uses: "stefanzweifel/git-auto-commit-action@v4"
         with:
